# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_address',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
